import { Conquista } from '../types/gamificacao';

export const CATALOGO_CONQUISTAS: Conquista[] = [
  // === ÓBVIAS (Marcos Esperados) ===
  {
    id: 'primeiro_treino',
    titulo: 'Primeira Suada',
    descricao: 'Completou o primeiro treino científico no Hypertropos. A jornada escultural começou.',
    icone: 'Barbell',
    tipo: 'obvia',
    xp_recompensa: 50,
  },
  {
    id: 'primeira_semana',
    titulo: 'Consistência Inicial',
    descricao: 'Manteve a rotina de treinos por uma semana completa. Uma base sólida está se formando.',
    icone: 'CalendarBlank',
    tipo: 'obvia',
    xp_recompensa: 100,
  },
  {
    id: 'primeiro_mes',
    titulo: 'Hábito Formado',
    descricao: 'Quatro semanas consecutivas de dedicação. A neuroplasticidade consolidou o hábito.',
    icone: 'CalendarHeart',
    tipo: 'obvia',
    xp_recompensa: 200,
  },
  {
    id: 'tres_meses',
    titulo: 'Estátua Resiliente',
    descricao: 'Doze semanas de treinos científicos. Seus músculos mostram adaptações mecânicas claras.',
    icone: 'ShieldCheck',
    tipo: 'obvia',
    xp_recompensa: 500,
  },
  {
    id: 'seis_meses',
    titulo: 'Materialidade Pura',
    descricao: 'Meio ano de consistência inabalável. Você esculpiu uma nova realidade física.',
    icone: 'Atom',
    tipo: 'obvia',
    xp_recompensa: 1000,
  },
  {
    id: 'primeira_progressao',
    titulo: 'Evolução Científica',
    descricao: 'Subiu de nível em um padrão de movimento. Sobrecarga progressiva na prática.',
    icone: 'TrendUp',
    tipo: 'obvia',
    xp_recompensa: 100,
  },
  {
    id: 'tier_pedra',
    titulo: 'Força Mineral',
    descricao: 'Sua estátua evoluiu para o Tier de Pedra. Quatro semanas de pura materialidade.',
    icone: 'Wall',
    tipo: 'obvia',
    xp_recompensa: 300,
  },
  {
    id: 'tier_marmore',
    titulo: 'Estética Clássica',
    descricao: 'Sua estátua alcançou o prestigioso Tier de Mármore. O ápice do design clássico.',
    icone: 'Crown',
    tipo: 'obvia',
    xp_recompensa: 500,
  },
  {
    id: 'tier_dourada',
    titulo: 'Ateu de Gravidade',
    descricao: 'Sua estátua brilha no Tier Dourado. Você dominou a física e a biologia corporal.',
    icone: 'Sparkles',
    tipo: 'obvia',
    xp_recompensa: 1000,
  },
  {
    id: 'streak_7',
    titulo: 'Chama Acesa',
    descricao: 'Completou um streak de 7 dias consecutivos. A dopamina está agindo.',
    icone: 'Flame',
    tipo: 'obvia',
    xp_recompensa: 100,
  },
  {
    id: 'streak_30',
    titulo: 'Inabalável',
    descricao: 'Atingiu a marca de 30 dias de streak. Imprevistos não pararam sua consistência.',
    icone: 'Lightning',
    tipo: 'obvia',
    xp_recompensa: 300,
  },
  {
    id: 'streak_100',
    titulo: 'Soberania Mecânica',
    descricao: 'Centenas de dias seguidos mantendo o streak. Uma lenda da gravidade.',
    icone: 'Trophy',
    tipo: 'obvia',
    xp_recompensa: 1000,
  },
  {
    id: 'primeira_meta_proteina',
    titulo: 'Síntese Ativa',
    descricao: 'Atingiu sua meta diária de proteína pela primeira vez. Hipertrofia requer combustível.',
    icone: 'Egg',
    tipo: 'obvia',
    xp_recompensa: 50,
  },
  {
    id: 'proteina_30',
    titulo: 'Nutrição Rigorosa',
    descricao: 'Manteve a meta de proteína por 30 dias seguidos. Síntese proteica otimizada.',
    icone: 'ListChecks',
    tipo: 'obvia',
    xp_recompensa: 300,
  },
  {
    id: 'primeira_creatina',
    titulo: 'Saturação Celular',
    descricao: 'Registrou o primeiro uso de Creatina Grau A. Seus estoques de fosfocreatina agradecem.',
    icone: 'Drop',
    tipo: 'obvia',
    xp_recompensa: 50,
  },
  {
    id: 'creatina_30',
    titulo: 'Efeito Grau A',
    descricao: 'Consumiu creatina por 30 dias consecutivos. Saturação celular completa atingida.',
    icone: 'Flask',
    tipo: 'obvia',
    xp_recompensa: 200,
  },

  // === SURPRESA (Recompensa Variável) ===
  {
    id: 'treino_madrugador',
    titulo: 'Madrugador de Aço',
    descricao: 'Concluiu um treino científico antes das 7:00 da manhã. Venceu o dia logo cedo.',
    icone: 'SunDim',
    tipo: 'surpresa',
    xp_recompensa: 50,
  },
  {
    id: 'treino_variado',
    titulo: 'Flexibilidade Caótica',
    descricao: 'Treinou em três horários diferentes em uma única semana. Adaptou-se e venceu.',
    icone: 'ClockCounterClockwise',
    tipo: 'surpresa',
    xp_recompensa: 50,
  },
  {
    id: 'cem_flexoes',
    titulo: 'Escudo Peitoral',
    descricao: 'Completou mais de 100 flexões em um único treino científico.',
    icone: 'Shield',
    tipo: 'surpresa',
    xp_recompensa: 100,
  },
  {
    id: 'duzentos_agachamentos',
    titulo: 'Pilar Grego',
    descricao: 'Completou mais de 200 agachamentos em um único treino científico. Pernas esculpidas.',
    icone: 'Columns',
    tipo: 'surpresa',
    xp_recompensa: 100,
  },
  {
    id: 'cadencia_perfeita',
    titulo: 'Precisão e Controle',
    descricao: 'Manteve a cadência perfeita e atingiu RIR exato em todas as séries de um treino.',
    icone: 'Target',
    tipo: 'surpresa',
    xp_recompensa: 100,
  },
  {
    id: 'primeiro_freeze',
    titulo: 'Escudo Temporal',
    descricao: 'Salvou seu streak utilizando 1 freeze pela primeira vez. A proteção funcionou.',
    icone: 'HourglassMedium',
    tipo: 'surpresa',
    xp_recompensa: 50,
  },
  {
    id: 'express_trio',
    titulo: 'Resiliência TDAH',
    descricao: 'Usou a Sessão Express 3 vezes em uma semana para salvar o streak. O ótimo é inimigo do bom.',
    icone: 'Bolt',
    tipo: 'surpresa',
    xp_recompensa: 100,
  },
  {
    id: 'leitor_ciencia',
    titulo: 'Mente Hipertrófica',
    descricao: 'Leu 5 artigos da seção Ciência. Conhecimento gera hipertrofia.',
    icone: 'BookOpen',
    tipo: 'surpresa',
    xp_recompensa: 100,
  },
  {
    id: 'primeira_leitura',
    titulo: 'Primeira Luz',
    descricao: 'Leu seu primeiro artigo científico no Hypertropos. A mente começou a crescer.',
    icone: 'GraduationCap',
    tipo: 'surpresa',
    xp_recompensa: 50,
  },
  {
    id: 'leitor_assiduo',
    titulo: 'Sábio da Sobrecarga',
    descricao: 'Completou 10 artigos lidos na seção de Ciência. Domínio teórico avançado.',
    icone: 'BookmarkSimple',
    tipo: 'surpresa',
    xp_recompensa: 200,
  },
  {
    id: 'bibliotecario',
    titulo: 'Mestre da Evidência',
    descricao: 'Leu todos os 18 artigos científicos do templo. Autoridade máxima em hipertrofia.',
    icone: 'Trophy',
    tipo: 'surpresa',
    xp_recompensa: 500,
  },
  {
    id: 'treino_completo_grupos',
    titulo: 'Estímulo Global',
    descricao: 'Ativou todos os 9 grupos musculares em uma única semana. Físico completo.',
    icone: 'GridFour',
    tipo: 'surpresa',
    xp_recompensa: 150,
  },
  {
    id: 'nivel_50',
    titulo: 'Veterano da Sobrecarga',
    descricao: 'Atingiu o nível 50 no Hypertropos. Uma marca digna dos deuses gregos.',
    icone: 'Medal',
    tipo: 'surpresa',
    xp_recompensa: 500,
  },
  {
    id: 'nivel_100',
    titulo: 'Lenda Clássica',
    descricao: 'Alcançou o nível 100. Sua consistência e força entraram para a história do templo.',
    icone: 'StarActive',
    tipo: 'surpresa',
    xp_recompensa: 1000,
  },
  {
    id: 'treino_adaptado',
    titulo: 'Adaptação Inteligente',
    descricao: 'Completou um treino com restrição articular ativa. Treinou com inteligência protetora.',
    icone: 'Heartbeat',
    tipo: 'surpresa',
    xp_recompensa: 100,
  },
  {
    id: 'atualizou_peso',
    titulo: 'Métrica Constante',
    descricao: 'Atualizou seu peso corporal no app. O que não é medido não é evoluído.',
    icone: 'Scale',
    tipo: 'surpresa',
    xp_recompensa: 50,
  },
];
