export type MicrocopyCategory =
  | 'transicao'
  | 'fimSessao'
  | 'streak'
  | 'conquistas'
  | 'tier'
  | 'falha'
  | 'cancelamento';

export const MICROCOPY_POOLS: Record<MicrocopyCategory, string[]> = {
  transicao: [
    "Sua atenção agora é o seu recurso mais valioso. Concentre-se na execução.",
    "Cada repetição é um estímulo mecânico único para a síntese de novas proteínas contráteis.",
    "O músculo não sabe contar; ele reconhece apenas o tempo sob tensão mecânica limite.",
    "A conexão mente-músculo não é metáfora: recrute intencionalmente cada fibra.",
    "Sinta o pico de contração na fase concêntrica. Controle a descida excêntrica.",
    "A fadiga que você sente agora é o sinal químico de que a adaptação está a caminho.",
    "Respire fundo. A oxigenação celular agora determina a eficiência da próxima série.",
    "Estabilize as articulações antes de iniciar o movimento. A técnica precede a carga.",
    "Mantenha a postura sólida. O alinhamento correto protege você e maximiza o torque.",
    "A constância na cadência de movimento ativa de forma mais eficiente as unidades motoras.",
    "Não busque o caminho mais fácil na repetição. Abrace a desvantagem mecânica.",
    "Sua força real é construída na zona onde a maioria das pessoas decide desacelerar.",
    "Visualize a trajetória perfeita do movimento antes mesmo de tensionar o primeiro músculo.",
    "Cada transição é a oportunidade de ajustar a técnica e focar no que realmente importa.",
    "A excelência física é a repetição sistemática de hábitos perfeitamente executados.",
    "O estresse mecânico controlado de hoje é a densidade muscular de amanhã.",
    "Ajuste os apoios, sinta o chão. A base firme é de onde brota a força verdadeira.",
    "Conexão neural ativa. Reduza as distrações ao seu redor e olhe para dentro.",
    "Cada exercício é um teste de foco. Deixe as preocupações fora da área de treino.",
    "O estímulo correto substitui o volume excessivo. Treine com intenção inteligente.",
    "Respeite o plano de treino. Cada movimento foi estrategicamente desenhado para você.",
    "A postura não é apenas estética; é a transferência eficiente de energia no exercício.",
    "Esqueça o ritmo externo. Encontre o compasso da sua própria respiração e controle.",
    "Você está no controle da carga, nunca o contrário. Domine cada centímetro do curso.",
    "A contração voluntária máxima nas repetições finais é o que separa o progresso do platô."
  ],
  
  fimSessao: [
    "Estímulo fisiológico gerado com sucesso. Agora, a síntese proteica e o descanso assumem.",
    "Sessão concluída. Mais um tijolo assentado na construção da sua consistência física.",
    "O trabalho duro do dia está feito. Nutra o seu corpo e permita a regeneração tecidual.",
    "Treinar é quebrar; descansar é construir. Você deu o primeiro passo, agora recupere-se.",
    "O dever foi cumprido com rigor técnico. Sua disciplina é a sua maior aliada.",
    "Mais uma sessão de alta qualidade para o seu histórico de evolução. O hábito se fortalece.",
    "Sua musculatura foi desafiada com inteligência. Orgulhe-se da postura mantida até o fim.",
    "Sessão finalizada. A sensação de dever cumprido é o melhor combustível dopaminérgico.",
    "O corpo responde à demanda que você impõe. Hoje você exigiu evolução, e ela virá.",
    "Cada treino finalizado é um voto de confiança na sua saúde e longevidade física.",
    "Você venceu a inércia mais uma vez. A consistência silenciosa gera resultados barulhentos.",
    "Treino finalizado com sucesso. Mantenha-se hidratado e priorize a qualidade do seu sono.",
    "A fadiga de agora é a força estrutural de amanhã. Excelente trabalho na sessão.",
    "O suor evapora, mas a adaptação neuromuscular permanece gravada na sua fisiologia.",
    "Você desafiou seus limites hoje e venceu. A jornada é feita de pequenos passos como este.",
    "Mais uma sessão integrada ao seu estilo de vida. O progresso é inevitável com essa constância.",
    "Foco mantido do início ao fim. Esse nível de dedicação esculpe corpos e mentes fortes.",
    "Estímulo mecânico de alta qualidade entregue. O descanso de hoje é o treino forte de amanhã.",
    "Sua musculatura agradece a dedicação. A transformação ocorre na consistência de cada dia.",
    "Sessão encerrada com louvor. Seu corpo está mais forte do que quando você começou hoje."
  ],
  
  streak: [
    "A chama da consistência continua acesa. Cada dia consecutivo fortalece o hábito neural.",
    "A consistência diária molda a identidade de quem não aceita desculpas fáceis.",
    "Sua sequência ativa é o reflexo prático do seu compromisso com sua própria evolução.",
    "Não quebre a corrente. O hábito consolidado exige menos esforço a cada novo dia.",
    "Dias difíceis testam o hábito; dias bons colhem o progresso. Continue na sequência.",
    "Sua regularidade é inspiradora. A constância vence o talento e a motivação passageira.",
    "Cada dia na sua sequência de treinos é uma vitória sobre a auto-sabotagem diária.",
    "A sequência de treinos cria um momento inercial que torna a desistência impensável.",
    "Mais um dia de vitória. A disciplina é o hábito de fazer o que precisa ser feito.",
    "Você está construindo uma muralha de consistência. Continue adicionando pedras diariamente.",
    "A regularidade é o segredo mais aberto e negligenciado da transformação física.",
    "Manter o ritmo quando a motivação falha é a verdadeira definição de maturidade atlética.",
    "Sua sequência está gerando adaptações metabólicas profundas e duradouras.",
    "O hábito automatizado é o superpoder da mente humana. Continue no trilho certo.",
    "Proteger sua sequência de treinos é proteger o investimento na sua saúde futura.",
    "Cada dia consecutivo é um tijolo a mais na sua fundação de autoconfiança física.",
    "A constância gera um ciclo virtuoso de energia, foco e vigor físico. Mantenha a chama.",
    "Você não está apenas treinando; você está reescrevendo o seu padrão de comportamento diário.",
    "O impulso está do seu lado. É mais fácil manter o movimento do que recomeçar do zero.",
    "Sua consistência é a prova viva de que você assumiu as rédeas do seu próprio destino."
  ],
  
  conquistas: [
    "Seu sistema nervoso central adaptou-se com sucesso a um novo patamar de esforço físico.",
    "Esta conquista é o selo oficial de que seu esforço superou as barreiras da adaptação.",
    "Seu corpo mudou porque suas escolhas forçaram essa mudança. Parabéns pela conquista.",
    "Desbloqueio merecido. A evolução física não é fruto do acaso, mas da precisão contínua.",
    "Você atingiu uma marca reservada àqueles que praticam a consistência de forma obstinada.",
    "Seu progresso estático foi quebrado por ações dinâmicas recorrentes. Excelente marco.",
    "O esforço invisível de cada treino agora se materializou em um marco visível de progresso.",
    "Adaptação neuromuscular de alto nível confirmada. Você elevou o seu padrão físico.",
    "Novos patamares exigem novas atitudes. Esta conquista prova que você está pronto para mais.",
    "A escultura de si mesmo exige paciência e o cinzel da disciplina diária. Belo progresso.",
    "Você venceu o platô. Cada conquista é a evidência biológica do seu trabalho duro.",
    "Seu corpo está aprendendo a ser mais eficiente, forte e resiliente. Parabéns pela marca.",
    "Esta medalha representa horas de foco silencioso e dedicação que ninguém mais viu.",
    "O sucesso é a soma de pequenos esforços repetidos dia após dia. Esta conquista é sua.",
    "A barreira do impossível acabou de ser empurrada um pouco mais para trás pelo seu esforço.",
    "Você provou a si mesmo que a dedicação é a única moeda que compra a evolução real.",
    "Seus músculos estão se adaptando, sua mente está se fortalecendo. O marco foi alcançado.",
    "Esta conquista é a prova de que você escolheu o caminho do crescimento e da superação.",
    "O hábito se transformou em resultado mensurável. Continue expandindo seus limites.",
    "Você conquistou o direito de se orgulhar do seu esforço. O progresso é inegável."
  ],
  
  tier: [
    "Sua silhueta agora reflete a densidade do esforço acumulado em cada série feita.",
    "A escultura física exige consistência, paciência e o material correto: sua dedicação.",
    "Transição de Tier confirmada. A matéria bruta de ontem é a estrutura refinada de hoje.",
    "Sua representação física no app evoluiu, espelhando a reconstrução interna de suas fibras.",
    "Subir de Tier é a confirmação visual de que suas células musculares foram remodeladas.",
    "A densidade e a definição do seu progresso agora ganham uma nova textura visual.",
    "Cada novo nível de tier é esculpido com o suor de séries levadas ao limite técnico.",
    "Seu progresso físico agora se traduz em uma forma mais imponente e lapidada.",
    "Da argila ao bronze, do bronze ao mármore: a jornada estética é um processo de refino.",
    "O Tier atual reflete as horas de treino inteligente que você acumulou com persistência.",
    "Sua estética evolutiva ganhou um novo brilho. Sinta a mudança e continue firme.",
    "A transformação externa é o espelho exato do fortalecimento interno de sua vontade.",
    "Seu corpo físico está mudando e o seu avatar acompanha essa metamorfose estrutural.",
    "Subir de tier é uma honra reservada aos consistentes. Você conquistou essa nova forma.",
    "As linhas da sua evolução estão mais nítidas, densas e equilibradas. Excelente transição.",
    "Sua silhueta no app é o monumento digital ao seu esforço real nas paredes de casa.",
    "Cada fibra tensionada com técnica contribuiu para este salto na sua representação física.",
    "O metal do seu avatar agora é mais nobre, denso e resistente. Reflexo do seu esforço.",
    "O cinzel da disciplina esculpiu mais uma fase. Mantenha o trabalho sob tensão mecânica.",
    "Você elevou a sua arquitetura corporal. Contemple sua nova silhueta e mire no próximo nível."
  ],
  
  falha: [
    "A falha concêntrica voluntária recruta as unidades motoras de mais alto limiar de força.",
    "Falhar com técnica excelente é o sinal fisiológico de que você explorou o limite das fibras.",
    "A hipertrofia ocorre no limiar da falha mecânica. Você entregou o estímulo perfeito.",
    "Não tema a falha; ela é o indicador de que o recrutamento de fibras de contração rápida foi máximo.",
    "Chegar ao limite da série com técnica preservada é onde a mágica da hipertrofia acontece.",
    "A falha mecânica temporária é a faísca que aciona a cascata de sinalização anabólica intracelular.",
    "Você encontrou o seu limite real hoje. É a partir dele que o corpo reconstrói fibras mais fortes.",
    "Parar antes da falha mecânica real é deixar o progresso na mesa. Excelente série levada ao limite.",
    "A incapacidade momentânea de mover a carga é a prova de que você exauriu as reservas de ATP-CP.",
    "A falha não é erro; na musculação científica, a falha é o objetivo máximo de estímulo mecânico.",
    "Seu esforço na última repetição recrutou até as fibras mais profundas e resistentes.",
    "A tensão limite gerada na falha força o corpo a se adaptar e hipertrofiar para o próximo treino.",
    "Você buscou a repetição limite e a encontrou. Esse é o caminho mais curto para a evolução física.",
    "A fadiga periférica acumulada na série é o estresse metabólico necessário para o crescimento.",
    "O limite físico alcançado com segurança é o ápice do treinamento de força inteligente.",
    "A série que desafia a falha é a que aciona a expressão gênica para síntese de novas miofibrilas.",
    "Você exigiu o máximo das pontes cruzadas de actina e miosina. O estímulo de hoje foi impecável.",
    "Respeite a falha mecânica. Ela sinaliza que o estímulo de adaptação foi completamente entregue.",
    "A exaustão muscular local controlada é o gatilho biológico para o aumento da densidade.",
    "Série fechada no limiar de esforço real. Esse nível de intensidade estimula o progresso sustentado.",
    "Seus músculos falharam temporariamente para que sua força cresça permanentemente.",
    "Sinal de recrutamento máximo enviado ao córtex motor. Você treinou como um atleta sério.",
    "A última repetição incompleta vale mais do que dez repetições fáceis que não desafiam o músculo.",
    "Intensidade técnica irretocável. Você explorou a amplitude total até o limite mecânico real.",
    "Fibras exauridas com precisão. O estímulo para a supercompensação foi ativado com sucesso."
  ],
  
  cancelamento: [
    "Um treino incompleto ou abreviado é infinitamente melhor do que um treino não realizado.",
    "A consistência a longo prazo aceita dias de volume reduzido. O importante é manter o hábito.",
    "O hábito neural de iniciar e fazer o que é possível protege você da inércia da desistência.",
    "Não há espaço para culpa. Adaptar o treino ao seu dia é um sinal de maturidade e longevidade.",
    "Consistência não significa perfeição rígida, mas sim a flexibilidade de persistir sempre.",
    "Você fez o que era viável para o dia de hoje. Essa pequena vitória mantém o seu cérebro no trilho.",
    "O acúmulo de estímulos parciais ao longo do ano constrói um físico muito melhor do que a inação.",
    "O importante é não perder a conexão com a sua rotina de saúde. Amanhã é uma nova oportunidade.",
    "Você protegeu o seu streak mental ao comparecer e fazer sua parte. Nos vemos na próxima sessão.",
    "Treinar um pouco é manter a identidade ativa de quem se cuida. Orgulhe-se por não ter zerado o dia.",
    "Respeite as demandas externas e o seu corpo. Saber parar no momento certo evita lesões e exaustão.",
    "O hábito de se movimentar foi mantido. A longo prazo, a constância supera picos isolados de esforço.",
    "Sua saúde é um projeto para a vida toda, não um sprint de uma semana. Ajustes fazem parte.",
    "Você marcou presença hoje. Esse esforço parcial acumula juros de saúde no seu banco biológico.",
    "O treino de hoje acabou mais cedo, mas o compromisso com o seu bem-estar continua inabalável.",
    "Consistência imperfeita ainda é consistência. Você está de parabéns por ter feito o que pôde.",
    "A jornada continua. Cada série executada hoje foi registrada e conta para sua evolução muscular.",
    "O cansaço ou a falta de tempo não venceram você por completo; você veio e fez o que era possível.",
    "Não quebre o compromisso com você mesmo. A consistência flexível é o segredo dos veteranos.",
    "Sessão encerrada com maturidade. O descanso e a gestão de rotina também fazem parte do ganho físico."
  ]
};

export const FRASES_FINAL_SESSAO = MICROCOPY_POOLS.fimSessao;
export const FRASES_ENTRE_EXERCICIOS = MICROCOPY_POOLS.transicao;
