export const FRASES_ENTRE_EXERCICIOS = [
  'Mandou bem!',
  'Tensão pura.',
  'Tijolo por tijolo.',
  'Tensão gera adaptação.',
  'Fibra por fibra.',
  'Construindo o templo.',
  'Aço temperado.',
  'Mais um passo.',
  'Sem atalhos.',
  'Foco no movimento.',
  'Tensão mecânica máxima!',
  'Mente no músculo.',
  'Superando limites.',
  'Força esculpida.',
  'Cinzelando o corpo.',
  'Arranhando o limite.',
  'Controle o peso.',
  'Sinta a contração.',
  'A evolução é lenta, mas constante.',
  'Não pare agora!',
  'Qualidade sobre quantidade.',
  'Estímulo puro.',
  'Foco na excêntrica.',
  'Cadência controlada.',
  'Conexão mente-músculo.',
  'Consistência é a chave.',
  'Cada repetição conta.',
  'Execução impecável.',
  'Adaptação hipertrófica.',
  'Busque o esforço.',
  'Mais perto do alvo.',
  'Trabalho feito!',
  'Aço em construção.',
  'Série por série.',
  'Volume acumulado com sucesso.',
  'Estímulo mecânico de alta precisão.',
  'Mais uma vitória sobre a gravidade.',
  'Controle absoluto da carga.',
  'Fibras musculares ativadas!',
  'Cinzelando com disciplina.'
];

export const FRASES_FINAL_SESSAO = [
  'Você esculpiu mais uma obra de arte hoje.',
  'Sessão concluída! O templo está mais forte.',
  'Tensão mecânica acumulada com sucesso.',
  'Cada gota de suor é um cinzel batendo na rocha.',
  'Você dominou a gravidade hoje. Parabéns!',
  'Sessão brilhante. A consistência protege seu streak.',
  'Treino impecável. Adaptação hipertrófica ativada com sucesso.',
  'Você venceu a inércia e alimentou a sua evolução.',
  'Trabalho duro finalizado. Agora, nutra o seu progresso.',
  'Mais um tijolo assentado na sua muralha física.',
  'Estímulo de alto impacto concluído. Descanse e cresça.',
  'Você honrou sua rotina hoje. O físico do futuro agradece.',
  'Hipertrofia científica em ação. Mais uma sessão para a conta!',
  'Foco, cadência e consistência. Você entregou tudo hoje.',
  'A silhueta se define na constância. Execução perfeita!'
];

export const FRASES_FALHA_PROXIMA = [
  'Falha real atingida. Recrutamento de unidades motoras maximizado!',
  'RIR 0: Recrutamento total de fibras de alto limiar!',
  'Até o limite. Tensão mecânica extrema induzida!',
  'Falha concêntrica iminente. Sinalização hipertrófica no pico!',
  'RIR 0: A fronteira do crescimento muscular foi superada!'
];
